# Site settings
title: LiewJunTung
email: pandawarrior91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  That's my name alright
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pandawarrior91.github.io" # the base hostname & protocol for your site
twitter_username: pandawarrior
github_username:  pandawarrior91

# Build settings
markdown: kramdown
kramdown:
  input: GFM
port: 8080
